### ISSUE TITLE
Error or misunderstanding of the graphs?

### ISSUE THREAD

**Issue by hans-ekbrand** [killerducky/lc0_blog_test#3]
![image](https://user-images.githubusercontent.com/551014/51411782-674b1280-1b69-11e9-86ee-c94c6e4878c4.png)
This is the policy distribution, so we expect lc0 to start exploring h6. However, according to (my interpretation of) this graph:
![image](https://user-images.githubusercontent.com/551014/51411867-cad54000-1b69-11e9-9154-3c808e2c611b.png)
b6 was the first move explored. Do I misunderstand the "Child Node Visits vs Total Nodes"?

**Comment by killerducky** [comment]
Can you upload the data.html file?

**Comment by hans-ekbrand** [comment]
Sure, I'll do it on discord (I can only upload image files here, I think).
